<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div>
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">Reports</h2>
                <p class="text-sm text-gray-500">
                    Daily reports (PDF). Retention: last 6 months.
                    <span class="block sm:inline">
                        Report Date = the day the report is for, Generated At = the time you clicked generate / scheduler ran.
                    </span>
                </p>
            </div>

            @can('reports.generate')
                <form method="POST" action="{{ route('reports.generateNow') }}">
                    @csrf
                    <button class="px-4 py-2 rounded bg-indigo-600 text-white text-sm hover:bg-indigo-700">
                        Generate Today Report
                    </button>
                </form>
            @endcan
        </div>
    </x-slot>

    <div class="py-8">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            @if(session('success'))
                <div class="mb-4 p-3 rounded bg-green-50 text-green-800 border border-green-200">
                    {{ session('success') }}
                </div>
            @endif

            @if(session('error'))
                <div class="mb-4 p-3 rounded bg-red-50 text-red-800 border border-red-200">
                    {{ session('error') }}
                </div>
            @endif

            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg border">
                <div class="p-6">

                    <div class="overflow-x-auto">
                        <table class="min-w-full text-sm">
                            <thead>
                                <tr class="text-left text-gray-600 border-b">
                                    <th class="py-2">Report Date</th>
                                    <th class="py-2">Generated By</th>
                                    <th class="py-2">Generated At</th>
                                    <th class="py-2 text-right">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @forelse($reports as $r)
                                    <tr class="border-b">
                                        <td class="py-3 font-semibold">
                                            {{-- Show only date even if DB column is datetime --}}
                                            {{ \Illuminate\Support\Carbon::parse($r->report_date)->toDateString() }}
                                        </td>

                                        <td class="py-3">
                                            {{ $r->generator?->name ?? '-' }}
                                        </td>

                                        <td class="py-3">
                                            <div class="font-medium text-gray-800">
                                                {{ $r->created_at?->format('Y-m-d H:i') }}
                                            </div>
                                            <div class="text-xs text-gray-500">
                                                {{ $r->created_at?->diffForHumans() }}
                                            </div>
                                        </td>

                                        <td class="py-3 text-right">
                                            @can('reports.download')
                                                <a href="{{ route('reports.download', $r) }}"
                                                   class="px-3 py-1 rounded bg-gray-100 hover:bg-gray-200 inline-flex items-center gap-2">
                                                    <span>Download PDF</span>
                                                </a>
                                            @endcan
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="4" class="py-10 text-center text-gray-500">
                                            No reports yet. Click “Generate Today Report”.
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                    <div class="mt-4">
                        {{ $reports->links() }}
                    </div>

                </div>
            </div>

        </div>
    </div>
</x-app-layout>
